version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project

jobs:
  test:
    executor: default-executor
    steps:
      - checkout
      - run:
          name: Run Tests
          command: echo "Running tests..."

workflows:
  version: 2
  test_workflow:
    jobs:
      - test
